// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, user_id, message)
VALUES (
  gen_random_uuid(), now(), now(), $1, $2
)
RETURNING id, created_at, updated_at, user_id, message
`

type CreateChirpParams struct {
	UserID  uuid.UUID
	Message string
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.UserID, arg.Message)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Message,
	)
	return i, err
}

const getChirp = `-- name: GetChirp :one
SELECT id, created_at, updated_at, user_id, message FROM chirps
WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Message,
	)
	return i, err
}

const listChirps = `-- name: ListChirps :many
SELECT id, created_at, updated_at, user_id, message FROM chirps
ORDER BY created_at ASC
`

func (q *Queries) ListChirps(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, listChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
